### ISSUE TITLE
gitup 0.88 doesn't build on FreeBSD 11.4 i386

### ISSUE THREAD

**Issue by nunotexbsd** [johnmehr/gitup#30]
Hello,

http://beefy10.nyi.freebsd.org/data/114i386-default/560826/logs/gitup-0.88.log

Any clues on this?
---
               if (read(fd, *buffer, *buffer_size) != *buffer_size)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
gitup.c:1006:3: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
                strlen(connection->agent) + 4,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gitup.c:1043:3: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
                strlen(connection->agent) + 4,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gitup.c:1099:3: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
                strlen(connection->agent) + 4,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gitup.c:1745:33: error: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Werror,-Wsign-compare]
        while (position - tree->buffer < tree->buffer_size) {
               ~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~
5 errors generated.
*** Error code 1
---

Thanks,

Nuno Teixeira

**Comment by johnmehr** [comment]
How does it look now?

**Comment by nunotexbsd** [comment]
I'm setting poudriere so I can test i386 target but I'm with internet connection issues, hope that I can test it today.

Thanks

**Comment by nunotexbsd** [comment]
My laptop refuses to let poudriere run i386 archs (only amd64) :(

I will try freebsd-ports to see if I get any help

**Comment by johnmehr** [comment]
Should I tag the last commit as 0.89 so the build process on beefy10 can be run again?  I've never used poudriere but I can get gitup to compile without errors by adding "-target i386-unknown-freebsd11.4" as a command-line parameter to cc so I think it's ok now.

**Comment by nunotexbsd** [comment]
Nice!

Please tag 0.89 so I can update port and submit it.

**Comment by johnmehr** [comment]
I just pushed the 0.89 tag.  Thank you!

**Comment by nunotexbsd** [comment]
I've just submit it, let's wait for a commiter.

Thanks

**Comment by nunotexbsd** [comment]
I've finally managed to get poudriere working and I can confirm that build is ok on 12.2 and 11.4 i386 arch :)

Thanks
