### ISSUE TITLE
Build failure on i386 arch (13.1 and 12.3)

### ISSUE THREAD

**Issue by nunotexbsd** [johnmehr/gitup#84]
Hello,

gitup 0.97 fails to build on i386 arch (13.1 and 12,3 rel):

===>  Building for gitup-0.97
echo gitup: /usr/lib/libc.a  >> .depend
Warning: Object directory not changed from original /wrkdirs/usr/ports/net/gitup/work/gitup-0.97
cc  -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -I/usr/include -DCONFIG_FILE_PATH=\"/usr/local/etc/gitup.conf\"   -MD  -MF.depend.gitup.o -MTgitup.o -std=gnu99 -Wno-format-zero-length -nobuiltininc -idirafter /usr/lib/clang/11.0.1/include -fstack-protector-strong -Wsystem-headers -Werror -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wold-style-definition -Wno-pointer-sign -Wmissing-variable-declarations -Wthread-safety -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable  -Qunused-arguments    -c gitup.c -o gitup.o
gitup.c:316:5: error: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Werror,-Wformat]
                                rd,
                                ^~
gitup.c:1372:5: error: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Werror,-Wformat]
                                total_bytes_sent);
                                ^~~~~~~~~~~~~~~~
gitup.c:1434:5: error: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Werror,-Wformat]
                                bytes_expected,
                                ^~~~~~~~~~~~~~
gitup.c:1435:5: error: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Werror,-Wformat]
                                total_bytes_read);
                                ^~~~~~~~~~~~~~~~
4 errors generated.
*** Error code 1

Full log: https://people.freebsd.org/~eduardo/logs/gitup-0.97/123i386_gitup-0.97.log

Any clue on how to fix build?

Thanks,

Nuno Teixeira

**Comment by johnmehr** [comment]
How does it work now?

**Comment by nunotexbsd** [comment]
Hello!

It builds fine on 12.3 i386 (Tier 1 / tested on poudriere).

Thank you very much,

Nuno Teixeira
